osx_image: xcode8.2
language: objective-c
before_install: rvm use 2.4 --install --binary --fuzzy
install: bundle install --without=documentation
before_script:
    - brew update
    - brew install carthage || true
    - brew install swiftlint || true
    - carthage bootstrap --platform all
script: make
after_success: slather
